### ISSUE TITLE
Falta documentación

### ISSUE THREAD

**Issue by MagicStar7213** [JatoMixo/Calculador_Examenes#1]
Probando el programa, sin saber **C#**, introduje los decimales con un **"."** en vez de con **","** y estos fueron tratados como **int**

Es por ello que pido permiso para una **pull-request** en la cual introduzco una nota a modo de recordatorio para no causar confusión, y que podrá ser revisada y editada para adaptarse a la apariencia e imagen del programa.

Además, sugiero añadir esta misma documentación al [README.md](../blob/main/README.md) para que sea más visual

Gracias

**Comment by JatoMixo** [comment]
Hola y gracias por el aviso.

He corregido el código para que salte una advertencia sobre el uso de comas en lugar de puntos al inicio del programa para que no se vuelva a dar este malentendido, y también he actualizado el README.md por el mismo motivo.

Muchas gracias de nuevo.
